sudo: false
language: node_js
node_js:
  - '0.12'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: f679......733c
    secure: HM+zrngQOwLgjTNvR7LHQnTZhw7XcY7LcrvKuH4dLoMPZTOHLr1iXWtAlJ5eqImvEReStkQzbrzEV/UzUug6QH+FPMiqoUh/nnjWJmznllbiq1Brt6cpRfjC2QXCG28ZgoRf7Agw9babA9x99Dk+hs/m9p2P2am12m7xD11VBZTo44aOzIE/6sBjMEXpdvY4jXSUdGoZ3g3GhFuSGqFRhSj1PXCxM9c4eb5vMD1VeUnJma5ZgbOjVaiwTfbTJDkRoDmEK5lmsvevfA5lYbeqlMoM8zuvE6w4Fvo9mwpFvbg9kCXtks2xy5BoPXKiz6xd8dDl3kprkk/mc90gmCdpJRn1xRJSMzDkjAMZR4mL4567kKeGqVctBLW0Ml+NEEZODDZ/58vy9J6MnXRjoGVl9fUXmdM+7Iz1CgOSj0OvzvY4fVEvSX0zwuzJm2ow/Uufa4dEwtMG52lZYtk1jQryNivCZTFDQR1ScpPJ+Qc7q2AIHxyAMqV47f0z6F+NwN4Tbf5u1hiygTwmIEVPJ76CRrpzlnuL6SHdS4+f8HYy1269GpyofnzzbyiHXGut7Qg7M4dYUr2EK6KqbShudbVS+9l3YVRYKkhDE2P8ht26TLYPokYqLjQFQyImy5qvc56WNb/7qWMCafJKeBcAZnzPVFW5nMorJ9FtmMPvia1yAvU=
  on:
    tags: true
    repo: Brightspace/eslint-config-brightspace
    all_branches: true
